### PR TITLE
Package updates for security

### PR DESCRIPTION
**Pull request by mribbons**
minimist@^1.2.3, https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
jest@^25.1.0, as per npm audit suggestion

### CODE REVIEW

**Comment by scottleibrand** [comment]
Just to confirm: the package-lock.json changes are also intentional?

**Comment by mribbons** [comment]
@scottleibrand That was the result of running npm install.

If we aren't using yarn, perhaps yarn.lock can be removed?

**Comment by scottleibrand** [comment]
I'm not an experienced developer myself, so I'm fine with both. Is this ready to merge now from your perspective?

**Comment by mribbons** [comment]
@scottleibrand good to go.
re yarn.lock: yarn recommends against using other package managers concurrently, but yarn is much faster than npm.

**Pull request merged**
